let dict = {
    智能ABC: {
        q: ["q", "ei"],
        w: ["w", "ian"],
        e: ["ch", "e"],
        r: ["r", "iu", "er"],
        t: ["t", "iang", "uang"],
        y: ["y", "ing"],
        u: ["u"],
        i: ["i"],
        o: ["o", "uo"],
        p: ["p", "uan"],
        a: ["zh", "a"],
        s: ["s", "ong", "iong"],
        d: ["d", "ia", "ua"],
        f: ["f", "en"],
        g: ["g", "eng"],
        h: ["h", "ang"],
        j: ["j", "an"],
        k: ["k", "ao"],
        l: ["l", "ai"],
        z: ["z", "iao"],
        x: ["x", "ie"],
        c: ["c", "in", "uai"],
        v: ["sh", "ve", "v"],
        b: ["b", "ou"],
        n: ["n", "un"],
        m: ["m", "ue", "ui"],
    },
    微软双拼: {
        q: ["q", "iu"],
        w: ["w", "ia", "ua"],
        e: ["e"],
        r: ["r", "uan", "er"],
        t: ["t", "ue"],
        y: ["y", "uai", "v"],
        u: ["sh", "u"],
        i: ["ch", "i"],
        o: ["o", "uo"],
        p: ["p", "un"],
        a: ["a"],
        s: ["s", "ong", "iong"],
        d: ["d", "iang", "uang"],
        f: ["f", "en"],
        g: ["g", "eng"],
        h: ["h", "ang"],
        j: ["j", "an"],
        k: ["k", "ao"],
        l: ["l", "ai"],
        ";": ["ing"],
        z: ["z", "ei"],
        x: ["x", "ie"],
        c: ["c", "iao"],
        v: ["zh", "ui", "ve"],
        b: ["b", "ou"],
        n: ["n", "in"],
        m: ["m", "ian"],
    },
    小鹤双拼: {
        q: ["q", "iu"],
        w: ["w", "ei"],
        e: ["e"],
        r: ["r", "uan", "van"],
        t: ["t", "ve", "ue"],
        y: ["y", "vn", "un"],
        u: ["sh", "u"],
        i: ["ch", "i"],
        o: ["o", "uo"],
        p: ["p", "ie"],
        a: ["a"],
        s: ["s", "ong", "iong"],
        d: ["d", "ai"],
        f: ["f", "en"],
        g: ["g", "eng"],
        h: ["h", "ang"],
        j: ["j", "an"],
        k: ["k", "uai", "ing"],
        l: ["l", "iang", "uang"],
        z: ["z", "ou"],
        x: ["x", "ia", "ua"],
        c: ["c", "ao"],
        v: ["zh", "ui", "v"],
        b: ["b", "in"],
        n: ["n", "iao"],
        m: ["m", "ian"],
    },
};

export const DoublePinyinDict = dict;
